### ISSUE TITLE
👨🏻‍💻 Add a section for "Benefits of Open source" ❗

### ISSUE THREAD

**Issue by sachin-duhan26** [learn-opensource/learn-opensource.github.io#2]
**Task Details** - Make a few Bootstrap cards with the following features :
1. Responsive 📱
2. Modern Style - 💎
3. Use Theme of the website only 🎯
4. Use of [SVG icon](https://www.flaticon.com/) to make it look fantastic.

```
🎁 Follow Open Community guidelines.
```

**Comment by utkarsh4321** [comment]
Hii @sachin-duhan26  can i work on this issue.

**Comment by sachin-duhan26** [comment]
Thank you for volunteering @utkarsh4321 ,

**Comment by utkarsh4321** [comment]
Hii @sachin-duhan26 can you explain me in brief where you want this section in your website. And if there any suggested design so please give it to me so I will implement according to your requirements. And if no give me any reference so I will see it and start working on it asap.

**Comment by vansh1999** [comment]
@sachin-duhan26 will try my best to work on these features

**Comment by sachin-duhan26** [comment]
Hello, @utkarsh4321 & @vansh1999,

Here are some inspirations and design motivations -
1. [ Link to template 🤞🏻  ](https://bootstrapmade.com/demo/MyResume/).
2. Visit the **Services section** on the website. Content can be replaced with the "Benefits of Open sources Contribution."💻
3. **Do not copy 🚫,**   use your own creativity.  

Also, here are some resources for Content 📝 
1. [Link 1](https://opensource.com/article/17/8/enterprise-open-source-advantages)
2. [Link 2](https://enterprisersproject.com/article/2015/1/top-advantages-open-source-offers-over-proprietary-solutions)

💯 Note - Use the **pagination** or **carousel** method if you are planning to use 6+ cards. Also, We Welcome any other creative ideas that you might be having...

**Comment by sachin-duhan26** [comment]
Hello, 
Just wanted to update you both that the code in the repo has been updated.  kindly pull the latest code 😄 before start contributing. 
```
$ git pull
```
Thanks ❤️

**Comment by vansh1999** [comment]
sure

**Comment by vansh1999** [comment]
@sachin-duhan26 completed the task , please check

**Comment by sachin-duhan26** [comment]
@utkarsh4321 thank you for devoting your time but @vansh1999 has already created a PR.
Considering your knowledge and experience I suggest you reviewing and working #7 or #5 

if you are interested, let me know 😄
