### ISSUE TITLE
[ UPDATE ] ☝🏻 Make Navbar Sticky 👻

### ISSUE THREAD

**Issue by sachin-duhan26** [learn-opensource/learn-opensource.github.io#3]
❤️ **| hacktoberfest2020 | Easy | contribution for beginners |** 🎧 

Probable Solutions : 
1. Use bootstrap class ☄️ ( [check here](https://getbootstrap.com/docs/4.0/components/navbar) )
2. Write custom CSS property 💯

**Comment by jscastanos** [comment]
Hi! I'd like to work on this issue.
