### ISSUE TITLE
[ FEATURE ] - Page for github Issues 🎯

### ISSUE THREAD

**Issue by sachin-duhan26** [learn-opensource/learn-opensource.github.io#5]
We wanted to update 💯  the [issues page](https://github.com/learn-opensource/learn-opensource.github.io/blob/master/issues.html) and add dynamic content using [Github API](https://api.github.com/orgs/learn-opensource), that fetch all available issues.🤺 

## REQUIREMENT OVERVIEW 🖥️ 
1. [ ] Update the [issues page](https://github.com/learn-opensource/learn-opensource.github.io/blob/master/issues.html).
2. [ ] Update main.js 🕺🏻  that with a call to GitHub API to fetch open issues at [learn-opensource](https://github.com/learn-opensource).
3. [ ] Display the response received on [issues page](https://github.com/learn-opensource/learn-opensource.github.io/blob/master/issues.html).

### OTHER DETAILS
- Responsiveness is a MUST.
-  a preloader & paginations is optional.

### ISSUE API URL
- [demo](https://api.github.com/repos/learn-opensource/learn-opensource.github.io/issues)

**Hint** - Flow for this issue is nearly the same as that for fetching projects in [main.js](https://github.com/learn-opensource/learn-opensource.github.io/blob/master/js/main.js) File.

**#hacktoberfest2020 👨🏻‍💻    #hacktoberfest ❤️**

**Comment by utkarsh4321** [comment]
Hi @sachin-duhan26 can I work on this issue

**Comment by utkarsh4321** [comment]
Hii @sachin-duhan26 what information are you want to see into issue page means issue title, assignee etc .or can you show me an example of it so I will implement it asap

**Comment by sachin-duhan26** [comment]
Hello @utkarsh4321 

## Attribute List
Below are required Attributes & details that are required to be displayed on the page
1. repo name
2. title
3. truncated body [150 words max ]
4. number of comments
5. labels [ with specific colors ]

### UI HINTS
- I have designed a [bootstrap card](https://codepen.io/sachin_duhan1/pen/rNLMLGG) for you.
- You can be creative in terms of designing the layout of the page.
- Abide by the theme of the website
